<ResultScreen>:
    MDBoxLayout:
        orientation: "vertical"
        MDLabel:
            halign: "center"
            size_hint: 1, 0.13
            text: "Tu puntaje es:"
        MDLabel:
            halign: "center"
            size_hint: 1, 0.12
            text: root.score
        ScrollView:
            size_hint: 1, 0.75
            MDList:
                id: results_list 
                size_hint_y: None 
                height: self.minimum_height 

